from app.repo.audio_master import (
    AudioAssemblyError,
    assemble_master,
    ffmpeg_available,
)
from app.repo.b2_client import (
    check_connectivity,
    delete_file,
    get_file_metadata,
    get_presigned_url,
    get_upload_stats,
    list_files,
    upload_file,
)
from app.repo.books_store import (
    delete_prefix,
    get_stream_url,
    list_prefixes,
    prefix_size,
    put_bytes,
    read_json,
    read_object,
    write_json,
)
from app.repo.job_queue import (
    JobLeaseError,
    JobQueueError,
    JobSecurityError,
    acquire_book_lease,
    acquire_resume_scan_lease,
    cancel_job,
    current_job_retries_left,
    enqueue_job,
    get_resume_scan_cursor,
    is_book_tombstoned,
    run_worker,
    set_resume_scan_cursor,
    tombstone_book,
)
from app.repo.tts import TTSError, TTSProvider, get_provider

__all__ = [
    "AudioAssemblyError",
    "JobLeaseError",
    "JobQueueError",
    "JobSecurityError",
    "TTSError",
    "TTSProvider",
    "acquire_book_lease",
    "acquire_resume_scan_lease",
    "assemble_master",
    "cancel_job",
    "check_connectivity",
    "current_job_retries_left",
    "delete_file",
    "delete_prefix",
    "enqueue_job",
    "ffmpeg_available",
    "get_file_metadata",
    "get_presigned_url",
    "get_provider",
    "get_resume_scan_cursor",
    "get_stream_url",
    "get_upload_stats",
    "is_book_tombstoned",
    "list_files",
    "list_prefixes",
    "prefix_size",
    "put_bytes",
    "read_json",
    "read_object",
    "run_worker",
    "set_resume_scan_cursor",
    "tombstone_book",
    "upload_file",
    "write_json",
]
